contract_form/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('form.urls')),
    path('quality/', include('quality.urls')),
    path('seller_details/', include('seller_details.urls')),
    path('buyer_details/', include('buyer_details.urls')),
    path('agent/', include('agent.urls')),
    path('transport/', include('transport.urls'))
]

form/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path("", NewForm.as_view(), name="Form-new"),
    path("view/", ViewForm.as_view(), name="Form-view"),
    path("update/<int:pk>", UpdateForm.as_view(), name="Form-update"),
    path("delete/<int:pk>", DeleteForm.as_view(), name="Form-delete"),
    path("download/<int:id>/", download, name="download")
]

form/models.py
from django.db import models
from django.urls import reverse
from buyer_details.models import *
from seller_details.models import *
from quality.models import *
from agent.models import *
from transport.models import *


class Form(models.Model):
    date = models.DateField()
    sellername = models.ForeignKey(
        Seller, on_delete=models.CASCADE)
    buyername = models.ForeignKey(
        Buyer, on_delete=models.CASCADE)
    agentname = models.ForeignKey(
        Agent, on_delete=models.CASCADE)
    Quality = models.ForeignKey(
        Quality, on_delete=models.CASCADE)
    reed = models.CharField(max_length=150, null=True, blank=True)
    pik = models.CharField(max_length=150, null=True, blank=True)
    width = models.CharField(max_length=150, null=True, blank=True)
    pcs = models.CharField(max_length=150, null=True, blank=True)
    discount = models.CharField(max_length=150, null=True, blank=True)
    rate = models.CharField(max_length=150, null=True, blank=True)
    quantity = models.CharField(max_length=150, null=True, blank=True)
    delivery_period = models.CharField(max_length=150, null=True, blank=True)
    payment_terms = models.CharField(max_length=150,  null=True, blank=True)
    transport = models.ForeignKey(Transport, on_delete = models.CASCADE)
    delivery_at = models.CharField(max_length=150, null=True, blank=True)
    remarks = models.CharField(max_length=150, null=True, blank=True)

    def __str__(self):
        return f"{self.sellername} {self.buyername}"

    def get_absolute_url(self):
        success_url = reverse('download', kwargs={'id': self.pk})
        return success_url

form/forms.py
from django import forms
from .models import Form

class FormModelForm(forms.ModelForm):
    class Meta:
        model = Form
        fields = '__all__'
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            # 'delivery_period': forms.DateInput(attrs={'type': 'date'}),
        }

form/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .forms import FormModelForm
from .models import Form
from django.urls import reverse
# Create your views here.


class NewForm(CreateView):
    model = Form
    form_class = FormModelForm
    


class ViewForm(ListView):
    model = Form
    context_object_name = 'Forms'


class UpdateForm(UpdateView):
    model = Form
    fields = '__all__'
    success_url = '/view'


class DeleteForm(DeleteView):
    model = Form
    success_url = '/view'


def download(request, id):
    object = Form.objects.get(id=id)
    return render(request, "form/form_print.html", {
        "object": object
    })

form/templates/form/form_form.html
{% load crispy_forms_field %}
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/x-icon" href="{% static '/image/chart.png' %}">
    <title>Kalpataru Trading Corporation</title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css'%}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- Include Select2 CSS and JS files -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />

</head>

<body class="bg-light">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'Form-new'%}">Kalpataru Trading Corporation</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
           <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Form-new'%}">New Form</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Buyer-new'%}">Add Buyer</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Seller-new'%}">Add Seller</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Quality-new'%}">Add Quality</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Agent-new'%}">Add Agent</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Transport-new'%}">Add Transport</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Form-view'%}">View Form</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="py-5 text-center">
            <img src="">
            <img class="d-block mx-auto mb-4" src="{% static '/image/logo.png' %}" alt="" width="72" height="72">
            <h2>Contract Form</h2>
        </div>

        <div class="row">
            <div class="col-md-8 order-md-2 mx-auto">
                <form class="needs-validation" method="post" id="myform">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Date </label>
                        {% crispy_field form.date class="form-control" %}
                    </div>

                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="sellername" class="form-label">Seller Name</label>
                            {% crispy_field form.sellername class="form-control" %}
                            <div class="invalid-feedback">
                                Please provide a valid seller name.
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="buyername" class="form-label">Buyer Name</label>
                            {% crispy_field form.buyername class="form-control" %}
                            <div class="invalid-feedback">
                                Please provide a valid buyer name.
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="buyername" class="form-label">Agent Name</label>
                            {% crispy_field form.agentname class="form-control" %}
                            <div class="invalid-feedback">
                                Please provide a valid Agent name.
                            </div>
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="Quality" class="form-label">Quality</label>
                        {% crispy_field form.Quality class="form-control" %}
                        <div class="invalid-feedback">
                            Please provide a valid quality.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="reed" class="form-label">Reed</label>
                        {% crispy_field form.reed class="form-control" %}
                        <div class="invalid-feedback">
                            Please provide a valid reed value.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="pik" class="form-label">Pik</label>
                        {% crispy_field form.pik class="form-control" %}
                        <div class="invalid-feedback">
                            Please provide a valid pik value.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="width" class="form-label">Width</label>
                        {% crispy_field form.width class="form-control" %}
                        <div class="invalid-feedback">
                            Please provide a valid width.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="width" class="form-label">Weight</label>
                        {% crispy_field form.pcs class="form-control" %}
                        <div class="invalid-feedback">
                            Please provide a valid width.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="width" class="form-label">Discount</label>
                        {% crispy_field form.discount class="form-control" %}
                        <div class="invalid-feedback">
                            Please provide a valid Discount.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="width" class="form-label">Rate</label>
                        {% crispy_field form.rate class="form-control" %}
                        <div class="invalid-feedback">
                            Please provide a valid Rate.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="width" class="form-label">Quantity</label>
                        {% crispy_field form.quantity class="form-control" %}
                        <div class="invalid-feedback">
                            Please provide a valid Quantity.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="delivery_period" class="form-label">Delivery Period (in days)</label>
                        {% crispy_field form.delivery_period class="form-control datepicker" %}
                        <div class="invalid-feedback">
                            Please provide a valid number of days for the delivery period.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="width" class="form-label">Payment Terms</label>
                        {% crispy_field form.payment_terms class="form-control" %}
                        <div class="invalid-feedback">
                            Please provide a valid Payment Terms.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="width" class="form-label">Transport</label>
                        {% crispy_field form.transport class="form-control" %}
                        <div class="invalid-feedback">
                            Please provide a valid Transport.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="width" class="form-label">Delivery at</label>
                        {% crispy_field form.delivery_at class="form-control" %}
                        <div class="invalid-feedback">
                            Please provide a valid Delivery at.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="width" class="form-label">Remark</label>
                        {% crispy_field form.remarks class="form-control" %}
                        <div class="invalid-feedback">
                            Please provide a valid Remarks.
                        </div>
                    </div>

                    <hr class="mb-4">
                    <button id="downloadBtn" class="btn btn-primary btn-lg btn-block" type="submit"
                        onclick="printForm()">Download and
                        Submit</button>
                </form>
            </div>
        </div>

        <footer class="my-5 pt-5 text-muted text-center text-small">
            <p class="mb-1">&copy; 2023-2024 <a href="https://shivam-mehta.web.app/">Shivam
                    Mehta</a>
            </p>
        </footer>
    </div>

</body>

<!-- Include jQuery -->
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script>
    
    $(document).ready(function () {
      
        $('#id_sellername').select2({
            placeholder: 'Search for a seller',
            width: '100%',
        });
        
        $('#id_buyername').select2({
            placeholder: 'Search for a buyer',
            width: '100%',
        });

        
        $('#id_agentname').select2({
            placeholder: 'Search for an agent',
            width: '100%',
        });

        
        $('#id_Quality').select2({
            placeholder: 'Search for a quality',
            width: '100%',
        });

        
        $('#id_transport').select2({
            placeholder: 'Search for a transport',
            width: '100%',
        });
    });
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js"></script>
</html>

form/templates/form/form_list.html
{% load crispy_forms_field %}
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static '/image/chart.png' %}">
    <title>Kalpataru Trading Corporation</title>
</head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'Form-new'%}">Kalpataru Trading Corporation</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Form-new'%}">New Form</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Buyer-new'%}">Add Buyer</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Seller-new'%}">Add Seller</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Quality-new'%}">Add Quality</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Agent-new'%}">Add Agent</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Form-view'%}">View Form</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="table-responsive-sm">
        <table class="table">

            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <!-- <th scope="col">Buyer Name</th> -->
                    <th scope="col">Seller Name</th>
                    <th scope="col">Date</th>
                    <th scope="col">View</th>
                </tr>
            </thead>
            <tbody>
                {% for Forms in Forms %}
                <tr>

                    <td>{{ Forms.id }}</td>
                    <!-- <td>{{ Forms.buyername }}</td> -->
                    <td>{{ Forms.sellername}}</td>
                    <td>{{ Forms.date }}</td>
                    <td>
                        <a class="btn btn-info btn-sm" href="{% url 'Form-update' Forms.id %}">
                            <i class="fas fa-pencil-alt">
                            </i>
                            View
                        </a>
                        <a class="btn btn-info btn-sm" href="{% url 'download' Forms.id %}">
                            <i class="fas fa-print"></i> Print</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>

</html>

form/templates/form/form_print.html
{% load crispy_forms_field %}
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/x-icon" href="{% static '/image/chart.png' %}">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static '/css/formPrint.css'%}">
    <link rel="stylesheet" href="{% static '/css/formPrintResponsive.css'%}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<body class="formMainBody">

    <div class="formMainHeader">
        <div class="greetTextHead">
            <p>Shree Nakoda Bhairavay Namah</p>
        </div>
        <div class="mainHead">
            <div class="mhLeft">
                <img src="{% static '/image/logo.png' %}" alt="" width="72" height="72">
            </div>
            <div class="mhRight">
                <h2>Order Form </h2>
                <h3>Kalpataru Trading Corporation</h3>
                <span>ktcahmedabad@yahoo.com | +91 94265 01564</span>
            </div>
        </div>
    </div>
    
    <div class="formSellerInfo">
        <div class="SIFirstCol">
            <div class="SIBname">
                <h3><strong>Buyer Name</strong></h3>
                <span>{{object.buyername}}</span>
            </div>
            <div class="SIAname">
                <h3><strong>Agent Name</strong></h3>
                <span>{{object.agentname}}</span>
            </div>
        </div>
        <div class="SISecondCol">
            <div class="SISname">
                <h3><strong>Seller Name</strong></h3>
                <div class="SIScn">
                    <p>Name: </p>
                    <p>{{object.sellername}}</p>
                </div>
                <div class="SIScd">
                    <p>Date: </p>
                    <p>{{object.date}}</p>
                </div>
            </div>
        </div>
    </div>

    <table class="paymentInfoTable">
        <thead>
            <tr>
                <th>Qlty</th>
                <th>Width</th>
                <th>Weight</th>
                <th>Qty</th>
                <th>Rate</th>
                <th>Reed</th>
                <th>Pik</th>
                <th>Payment Terms</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{object.Quality}}</td>
                <td>{{object.width}}</td>
                <td>{{object.pcs}}</td>
                <td>{{object.quantity}}</td>
                <td>{{object.rate}}</td>
                <td>{{object.reed}}</td>
                <td>{{object.pik}}</td>
                <td>{{object.payment_terms}}</td>
            </tr>
        </tbody>
    </table>
    
    
    <div class="paymentBillContainer">
        <div class="paymentBill">
            <div class="pbInfo">
                <p>Transport</p>
                <p>{{object.transport}}</p>
            </div>
            <div class="pbInfo">
                <p>Discount</p>
                <p>{{object.discount}}</p>
            </div>
            <div class="pbInfo">
                <p>Delivery Period(in days)</p>
                <p>{{object.delivery_period}}</p>
            </div>
            <div class="pbInfo">
                <p>Delivery at</p>
                <p>{{object.delivery_at}}</p>
            </div>
            <div class="pbInfo">
                <p>Remarks</p>
                <p>{{object.remarks}}</p>
            </div>
        </div>
    </div>


    <footer class="footer">
        <h4>ADDRESS</h4>
        <p>Kalpataru Trading Corporation</p>
        <p>20, Shri Mahavir Cloth Market, <br>
            B/H New Cloth Market,<br>
            Kankaria Road, Ahmedabad.</p>
        <p><strong>Contact Number: +91 94265 01564</strong></p>
    </footer>
</body>
<script>
    window.addEventListener("load", window.print());
</script>

</html>